# Generated by Django 4.2.2 on 2023-06-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='views',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
