# Generated by Django 4.2.2 on 2023-06-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_house_image_alter_announcement_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='views',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
