# Generated by Django 4.2.2 on 2023-06-11 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0007_remove_house_announcement_announcement_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.house'),
        ),
    ]
