# Generated by Django 4.2.2 on 2023-06-11 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0010_rename_house_description_house_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='auction_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='max_bet',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='house',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='announcements.house'),
        ),
    ]
