# Generated by Django 4.2.2 on 2023-06-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0011_announcement_auction_completed_announcement_max_bet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='max_bet',
            field=models.IntegerField(default=0),
        ),
    ]
