# Generated by Django 4.2.2 on 2023-06-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0013_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='views',
            new_name='number_of_bets',
        ),
        migrations.AddField(
            model_name='announcement',
            name='bet_to_complete',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='announcement',
            name='sold_to',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
