# Generated by Django 4.2.2 on 2023-06-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0014_rename_views_announcement_number_of_bets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='number_of_bets',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
